name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Java e Maven
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Compilar o projeto
        working-directory: urbanity
        run: mvn clean package -DskipTests

      - name: Iniciar aplicação Spring Boot
        working-directory: urbanity
        run: |
          java -jar target/urbanity.jar &
          sleep 15

      - name: Executar testes automatizados
        working-directory: urbanity
        run: mvn test