name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Java e Maven
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Compilar o projeto (sem rodar testes)
        working-directory: urbanity
        run: mvn clean package -DskipTests

      - name: Iniciar aplicação localmente
        working-directory: urbanity
        run: |
          nohup java -jar target/urbanity-0.0.1-SNAPSHOT.jar > app.log 2>&1 &
          sleep 20  # Aguarda a inicialização da aplicação

      - name: Verificar se a aplicação está rodando
        working-directory: urbanity
        run: |
          for i in {1..30}; do
            if curl -s http://localhost:8080/denuncias; then
              echo "Aplicação rodando!"
              break
            fi
            sleep 2
          done

      - name: Executar testes automatizados
        working-directory: urbanity
        run: mvn test