name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Java e Maven
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Compilar o projeto
        working-directory: urbanity
        run: mvn clean package -DskipTests

      - name: Construir a imagem Docker
        working-directory: urbanity
        run: docker build -t urbanity-app .

      - name: Iniciar container
        working-directory: urbanity
        run: docker run -d -p 8080:8080 urbanity-app

      - name: Executar testes automatizados
        working-directory: urbanity
        run: mvn test