name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Java e Maven
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Compilar o projeto
        working-directory: urbanity
        run: mvn clean package

  deploy-staging:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Instalar Docker e Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose -y

      - name: Verificar Docker e Docker Compose
        run: |
          docker --version
          docker compose version

      - name: Verificar diretórios
        run: ls -a

      - name: Checkout do código
        uses: actions/checkout@v3
        with:
          path: .

      - name: Compilar o projeto
        working-directory: urbanity
        run: mvn clean package

      - name: Verificar saída do build
        working-directory: urbanity
        run: ls -l target

      - name: Deploy no ambiente Staging
        working-directory: urbanity
        run: docker compose -f docker-compose.yml up -d

  deploy-prod:
    needs: deploy-staging
    runs-on: ubuntu-latest
    steps:
      - name: Instalar Docker e Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose -y

      - name: Verificar Docker e Docker Compose
        run: |
          docker --version
          docker compose version

      - name: Deploy no ambiente Produção
        working-directory: urbanity
        run: cd urbanity && docker compose -f docker-compose.yml up -d
